// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_Application.Data;

#nullable disable

namespace Quiz_Application.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260214070144_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Application.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "1",
                            OrderNo = 1,
                            Text = "What is the capital of France?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "5,6,7",
                            OrderNo = 2,
                            Text = "Which of the following are programming languages?",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 3,
                            OrderNo = 3,
                            Text = "What does HTML stand for?",
                            Type = "ShortAnswer"
                        },
                        new
                        {
                            Id = 4,
                            OrderNo = 4,
                            Text = "Enter your phone number",
                            Type = "PhoneNumber"
                        },
                        new
                        {
                            Id = 5,
                            OrderNo = 5,
                            Text = "Explain the concept of Object-Oriented Programming in detail.",
                            Type = "LongAnswer"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "11",
                            OrderNo = 6,
                            Text = "Which planet is known as the Red Planet?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "14,15,17",
                            OrderNo = 7,
                            Text = "Select all prime numbers from the list below.",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 8,
                            OrderNo = 8,
                            Text = "What is the chemical symbol for water?",
                            Type = "ShortAnswer"
                        });
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Text = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Text = "London"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Text = "Berlin"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 1,
                            Text = "Madrid"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 2,
                            Text = "C#"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 2,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 2,
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 2,
                            Text = "Photoshop"
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 6,
                            Text = "Venus"
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 6,
                            Text = "Jupiter"
                        },
                        new
                        {
                            Id = 11,
                            QuestionId = 6,
                            Text = "Mars"
                        },
                        new
                        {
                            Id = 12,
                            QuestionId = 6,
                            Text = "Saturn"
                        },
                        new
                        {
                            Id = 13,
                            QuestionId = 7,
                            Text = "4"
                        },
                        new
                        {
                            Id = 14,
                            QuestionId = 7,
                            Text = "7"
                        },
                        new
                        {
                            Id = 15,
                            QuestionId = 7,
                            Text = "11"
                        },
                        new
                        {
                            Id = 16,
                            QuestionId = 7,
                            Text = "9"
                        },
                        new
                        {
                            Id = 17,
                            QuestionId = 7,
                            Text = "13"
                        });
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("UserResponses");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.QuestionOption", b =>
                {
                    b.HasOne("Quiz_Application.Models.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserResponse", b =>
                {
                    b.HasOne("Quiz_Application.Models.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quiz_Application.Models.Entities.UserSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
