// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_Application.Data;

#nullable disable

namespace Quiz_Application.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Application.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "1",
                            OrderNo = 1,
                            Text = "What is the capital of France?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "11",
                            OrderNo = 6,
                            Text = "Which planet is known as the Red Planet?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "21",
                            OrderNo = 9,
                            Text = "What is the largest ocean on Earth?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswer = "31",
                            OrderNo = 13,
                            Text = "Who painted the Mona Lisa?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswer = "39",
                            OrderNo = 17,
                            Text = "What is the speed of light approximately?",
                            Type = "SingleChoice"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "5,6,7",
                            OrderNo = 2,
                            Text = "Which of the following are programming languages?",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "14,15,17",
                            OrderNo = 7,
                            Text = "Select all prime numbers from the list below.",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "25,26,27",
                            OrderNo = 10,
                            Text = "Which of these are JavaScript frameworks?",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswer = "33,34,35",
                            OrderNo = 14,
                            Text = "Which of these are database systems?",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            Id = 3,
                            OrderNo = 3,
                            Text = "What does HTML stand for?",
                            Type = "ShortAnswer"
                        },
                        new
                        {
                            Id = 8,
                            OrderNo = 8,
                            Text = "What is the chemical symbol for water?",
                            Type = "ShortAnswer"
                        },
                        new
                        {
                            Id = 11,
                            OrderNo = 11,
                            Text = "What is the square root of 144?",
                            Type = "ShortAnswer"
                        },
                        new
                        {
                            Id = 15,
                            OrderNo = 15,
                            Text = "What does CSS stand for?",
                            Type = "ShortAnswer"
                        },
                        new
                        {
                            Id = 4,
                            OrderNo = 4,
                            Text = "Enter your phone number",
                            Type = "PhoneNumber"
                        },
                        new
                        {
                            Id = 12,
                            OrderNo = 12,
                            Text = "Enter your emergency contact number",
                            Type = "PhoneNumber"
                        },
                        new
                        {
                            Id = 18,
                            OrderNo = 18,
                            Text = "Enter your alternate mobile number",
                            Type = "PhoneNumber"
                        },
                        new
                        {
                            Id = 5,
                            OrderNo = 5,
                            Text = "Explain the concept of Object-Oriented Programming in detail.",
                            Type = "LongAnswer"
                        },
                        new
                        {
                            Id = 16,
                            OrderNo = 16,
                            Text = "Describe the difference between SQL and NoSQL databases.",
                            Type = "LongAnswer"
                        },
                        new
                        {
                            Id = 19,
                            OrderNo = 19,
                            Text = "What are the advantages of using cloud computing?",
                            Type = "LongAnswer"
                        },
                        new
                        {
                            Id = 20,
                            OrderNo = 20,
                            Text = "Explain the MVC architecture pattern and its benefits.",
                            Type = "LongAnswer"
                        });
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Text = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Text = "London"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Text = "Berlin"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 1,
                            Text = "Madrid"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 2,
                            Text = "C#"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 2,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 2,
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 2,
                            Text = "Photoshop"
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 6,
                            Text = "Venus"
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 6,
                            Text = "Jupiter"
                        },
                        new
                        {
                            Id = 11,
                            QuestionId = 6,
                            Text = "Mars"
                        },
                        new
                        {
                            Id = 12,
                            QuestionId = 6,
                            Text = "Saturn"
                        },
                        new
                        {
                            Id = 13,
                            QuestionId = 7,
                            Text = "4"
                        },
                        new
                        {
                            Id = 14,
                            QuestionId = 7,
                            Text = "7"
                        },
                        new
                        {
                            Id = 15,
                            QuestionId = 7,
                            Text = "11"
                        },
                        new
                        {
                            Id = 16,
                            QuestionId = 7,
                            Text = "9"
                        },
                        new
                        {
                            Id = 17,
                            QuestionId = 7,
                            Text = "13"
                        },
                        new
                        {
                            Id = 18,
                            QuestionId = 9,
                            Text = "Atlantic Ocean"
                        },
                        new
                        {
                            Id = 19,
                            QuestionId = 9,
                            Text = "Indian Ocean"
                        },
                        new
                        {
                            Id = 20,
                            QuestionId = 9,
                            Text = "Arctic Ocean"
                        },
                        new
                        {
                            Id = 21,
                            QuestionId = 9,
                            Text = "Pacific Ocean"
                        },
                        new
                        {
                            Id = 22,
                            QuestionId = 10,
                            Text = "Django"
                        },
                        new
                        {
                            Id = 23,
                            QuestionId = 10,
                            Text = "Laravel"
                        },
                        new
                        {
                            Id = 24,
                            QuestionId = 10,
                            Text = "Flask"
                        },
                        new
                        {
                            Id = 25,
                            QuestionId = 10,
                            Text = "React"
                        },
                        new
                        {
                            Id = 26,
                            QuestionId = 10,
                            Text = "Angular"
                        },
                        new
                        {
                            Id = 27,
                            QuestionId = 10,
                            Text = "Vue.js"
                        },
                        new
                        {
                            Id = 28,
                            QuestionId = 13,
                            Text = "Vincent van Gogh"
                        },
                        new
                        {
                            Id = 29,
                            QuestionId = 13,
                            Text = "Pablo Picasso"
                        },
                        new
                        {
                            Id = 30,
                            QuestionId = 13,
                            Text = "Michelangelo"
                        },
                        new
                        {
                            Id = 31,
                            QuestionId = 13,
                            Text = "Leonardo da Vinci"
                        },
                        new
                        {
                            Id = 32,
                            QuestionId = 14,
                            Text = "Photoshop"
                        },
                        new
                        {
                            Id = 33,
                            QuestionId = 14,
                            Text = "MySQL"
                        },
                        new
                        {
                            Id = 34,
                            QuestionId = 14,
                            Text = "PostgreSQL"
                        },
                        new
                        {
                            Id = 35,
                            QuestionId = 14,
                            Text = "MongoDB"
                        },
                        new
                        {
                            Id = 36,
                            QuestionId = 14,
                            Text = "Excel"
                        },
                        new
                        {
                            Id = 37,
                            QuestionId = 17,
                            Text = "150,000 km/s"
                        },
                        new
                        {
                            Id = 38,
                            QuestionId = 17,
                            Text = "500,000 km/s"
                        },
                        new
                        {
                            Id = 39,
                            QuestionId = 17,
                            Text = "300,000 km/s"
                        },
                        new
                        {
                            Id = 40,
                            QuestionId = 17,
                            Text = "1,000,000 km/s"
                        });
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("UserResponses");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.QuestionOption", b =>
                {
                    b.HasOne("Quiz_Application.Models.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.UserResponse", b =>
                {
                    b.HasOne("Quiz_Application.Models.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quiz_Application.Models.Entities.UserSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Quiz_Application.Models.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
